<?php
 //transactions
 define(SM_DATE,'Date');
 define(SM_OPERATION,'Operation');
 define(SM_FROM,'From');
 define(SM_TO,'To');
 define(SM_SUM,'Amount');
 define(SM_COMMENT,'Comment');
 define(SM_CONF,'Confirmations');
 define(SM_TRANS,'Transaction');
 define(SM_INTERNAL_MOVE,'Internal move');
 define(SM_INTERNAL_REFILL,'External refill');
 define(SM_REFRESH_TRANSACTIONS,'Refresh transactions');
 define(SM_TRANSACTIONS_LIST,'Transactions list:');

 define(SM_CONFIRMED,'Confirmed');
 define(SM_UNCONFIRMED,'Waiting confirmation');


?>
