<?php
 
 //transactions
 define(SM_DATE,'Дата');
 define(SM_OPERATION,'Операция');
 define(SM_FROM,'От кого');
 define(SM_TO,'Кому');
 define(SM_SUM,'Сумма');
 define(SM_COMMENT,'Комментарий');
 define(SM_CONF,'Подтверждения');
 define(SM_TRANS,'Транзакция');
 define(SM_INTERNAL_MOVE,'Внутренний перевод');
 define(SM_INTERNAL_REFILL,'Внешнее пополнение');
 define(SM_REFRESH_TRANSACTIONS,'Обновить транзакции');
 define(SM_TRANSACTIONS_LIST,'Список транзакций:');

 define(SM_CONFIRMED,'Подтверждено');
 define(SM_UNCONFIRMED,'Ожидает подтверждения');


?>